SST: SST::Simulation Class Reference
SST::Simulation Class Reference
Main control class for a SST Simulation.
#include <simulation.h>
Public Types
enum Mode_t { UNKNOWN, INIT, RUN, BOTH }
Type of Run Modes.
typedef std::map< SimTime_t, Clock * > clockMap_t
typedef std::map< SimTime_t, OneShot * > oneShotMap_t
typedef std::vector< std::string > statEnableList_t
typedef std::vector< Params > statParamsList_t
typedef std::map< ComponentId_t, statEnableList_t * > statEnableMap_t
typedef std::map< ComponentId_t, statParamsList_t * > statParamsMap_t
Public Member Functions
void printStatus (bool fullStatus)
Causes the current status of the simulation to be printed to stderr.
void processGraphInfo (ConfigGraph &graph, const RankInfo &myRank, SimTime_t min_part)
Processes the ConfigGraph to pull out any need information about relationships among the threads.
int performWireUp (ConfigGraph &graph, const RankInfo &myRank, SimTime_t min_part)
Converts a ConfigGraph graph into actual set of links and components.
void setStopAtCycle (Config *cfg)
Set cycle count, which, if reached, will cause the simulation to halt.
void initialize ()
Perform the init() phase of simulation.
void setup ()
Perform the setup() and run phases of the simulation.
void run ()
void finish ()
bool isIndependentThread ()
Mode_t getSimulationMode () const
Get the run mode of the simulation (e.g.
const SimTime_t & getCurrentSimCycle () const
Return the current simulation time as a cycle count.
SimTime_t getEndSimCycle () const
Return the end simulation time as a cycle count.
int getCurrentPriority () const
Return the current priority.
UnitAlgebra getElapsedSimTime () const
Return the elapsed simulation time as a time.
UnitAlgebra getFinalSimTime () const
Return the end simulation time as a time.
RankInfo getRank () const
Get this instance's parallel rank.
RankInfo getNumRanks () const
Get the number of parallel ranks in the simulation.
TimeConverter * registerClock (std::string freq, Clock::HandlerBase *handler)
Register a handler to be called on a set frequency.
TimeConverter * registerClock (const UnitAlgebra &freq, Clock::HandlerBase *handler)
void unregisterClock (TimeConverter *tc, Clock::HandlerBase *handler)
Remove a clock handler from the list of active clock handlers.
Cycle_t reregisterClock (TimeConverter *tc, Clock::HandlerBase *handler)
Reactivate an existing clock and handler.
Cycle_t getNextClockCycle (TimeConverter *tc)
Returns the next Cycle that the TImeConverter would fire.
TimeConverter * registerOneShot (std::string timeDelay, OneShot::HandlerBase *handler)
Register a OneShot event to be called after a time delay Note: OneShot cannot be canceled, and will always callback after the timedelay.
TimeConverter * registerOneShot (const UnitAlgebra &timeDelay, OneShot::HandlerBase *handler)
void insertActivity (SimTime_t time, Activity *ev)
Insert an activity to fire at a specified time.
Exit * getExit () const
Return the exit event.
const std::vector< SimTime_t > & getInterThreadLatencies ()
const SimTime_t getInterThreadMinLatency ()
uint64_t getTimeVortexMaxDepth () const
uint64_t getTimeVortexCurrentDepth () const
uint64_t getSyncQueueDataSize () const
Statistics::StatisticProcessingEngine * getStatisticsProcessingEngine (void) const
Return the Statistic Processing Engine associated with this Simulation.
LinkMap * getComponentLinkMap (ComponentId_t id) const
Return pointer to map of links for a given component id.
const ComponentInfoMap & getComponentInfoMap (void)
Returns reference to the Component Map.
Component * getComponent (const std::string &name) const
Returns the component with a given name.
Component * getComponent (const ComponentId_t &id) const
returns the component with the given ID
ComponentInfo * getComponentInfo (const std::string &name) const
ComponentInfo * getComponentInfo (const ComponentId_t &id) const
statEnableList_t * getComponentStatisticEnableList (const ComponentId_t &id) const
statParamsList_t * getComponentStatisticParamsList (const ComponentId_t &id) const
Introspector * getIntrospector (const std::string &name) const
Returns the Introspector with the given name.
void setOutputDirectory (std::string &outDir)
Set the output directory for this simulation.
std::string & getOutputDirectory ()
Returns the output directory of the simulation.
void requireEvent (std::string name)
Signifies that an event type is required for this simulation Causes to Factory to verify that the required event type can be found.
SimTime_t getNextActivityTime () const
Returns the time of the next item to be executed that is in the TImeVortex of the Simulation.
bool isWireUpFinished ()
Returns true when the Wireup is finished.
Static Public Member Functions
static Simulation * createSimulation (Config *config, RankInfo my_rank, RankInfo num_ranks, SimTime_t min_part)
Create new simulation.
static void shutdown ()
Used to signify the end of simulation.
static Simulation * getSimulation ()
Return a pointer to the singleton instance of the Simulation.
static void setSignal (int signal)
Sets an internal flag for signaling the simulation.
static TimeConverter * getMinPartTC ()
static TimeLord * getTimeLord (void)
Return the TimeLord associated with this Simulation.
static Output & getSimulationOutput ()
Return the base simulation Output class instance.
static Statistics::StatisticOutput * getStatisticsOutput ()
static void signalStatisticsBegin ()
static void signalStatisticsEnd ()
static SimTime_t getLocalMinimumNextActivityTime ()
Gets the minimum next activity time across all TimeVortices in the Rank.
static SharedRegionManager * getSharedRegionManager ()
Returns the Simulation's SharedRegionManager.
Friends
class Link
class Action
class Output
class SyncManager
void wait_my_turn_start ()
void wait_my_turn_end ()
Detailed Description
Main control class for a SST Simulation.
Provides base features for managing the simulation
Member Typedef Documentation
typedef std::map<SimTime_t, Clock*> SST::Simulation::clockMap_t
Map of times to clocks
typedef std::map<SimTime_t, OneShot*> SST::Simulation::oneShotMap_t
Map of times to OneShots
typedef std::vector<std::string> SST::Simulation::statEnableList_t
List of Enabled Statistics
typedef std::map<ComponentId_t, statEnableList_t*> SST::Simulation::statEnableMap_t
Map of Statistics that are requested to be enabled for a component defined in configGraph
typedef std::vector<Params> SST::Simulation::statParamsList_t
List of Enabled Statistics Parameters
typedef std::map<ComponentId_t, statParamsList_t*> SST::Simulation::statParamsMap_t
Map of Statistic Params for a component defined in configGraph
Member Enumeration Documentation
enum SST::Simulation::Mode_t
Type of Run Modes.
Enumerator
UNKNOWN
Unknown mode - Invalid for running
INIT
Initialize-only. Useful for debugging initialization and graph generation
RUN
Run-only. Useful when restoring from a checkpoint
BOTH
Default. Both initialize and Run the simulation
Member Function Documentation
Simulation * SST::Simulation::createSimulation (Config * config, RankInfo my_rank, RankInfo num_ranks, SimTime_t min_part) static
Create new simulation.
Parameters
config - Configuration of the simulation
my_rank - Parallel Rank of this simulation object
num_ranks - How many Ranks are in the simulation
const ComponentInfoMap& SST::Simulation::getComponentInfoMap (void) inline
Returns reference to the Component Map.
Returns reference to the Component ID Map
Referenced by SST::Introspector::getModelsByType().
Cycle_t SST::Simulation::getNextClockCycle (TimeConverter * tc)
Returns the next Cycle that the TImeConverter would fire.
References SST::Output::fatal(), SST::TimeConverter::getFactor(), and SST::Output::STDERR.
Referenced by SST::SubComponent::getNextClockCycle(), and SST::Component::getNextClockCycle().
std::string& SST::Simulation::getOutputDirectory () inline
Returns the output directory of the simulation.
Returns
Directory in which simulation outputs are placed
Mode_t SST::Simulation::getSimulationMode () const inline
Get the run mode of the simulation (e.g.
init, run, both etc)
void SST::Simulation::printStatus (bool fullStatus)
Causes the current status of the simulation to be printed to stderr.
Parameters
fullStatus - if true, call printStatus() on all components as well as print the base Simulation's status
References SST::Output::output(), SST::TimeVortex::print(), and SST::Output::STDERR.
void SST::Simulation::requireEvent (std::string name)
Signifies that an event type is required for this simulation Causes to Factory to verify that the required event type can be found.
Parameters
name fully qualified libraryName.EventName
References SST::Factory::RequireEvent().
Cycle_t SST::Simulation::reregisterClock (TimeConverter * tc, Clock::HandlerBase * handler)
Reactivate an existing clock and handler.
Returns
time when handler will next fire
References SST::Output::fatal(), SST::TimeConverter::getFactor(), and SST::Output::STDERR.
Referenced by SST::Component::reregisterClock().
void SST::Simulation::setOutputDirectory (std::string & outDir) inline
Set the output directory for this simulation.
Parameters
outDir Path of directory to place simulation outputs in
void SST::Simulation::setSignal (int signal) static
Sets an internal flag for signaling the simulation.
Used internally
void SST::Simulation::setStopAtCycle (Config * cfg)
Set cycle count, which, if reached, will cause the simulation to halt.
References SST::TimeLord::getSimCycles(), SST::TimeVortex::insert(), SST::Activity::setDeliveryTime(), and SST::Config::stopAtCycle.
void SST::Simulation::setup ()
Perform the setup() and run phases of the simulation.
References SST::Core::ThreadSafe::Barrier::wait().
void SST::Simulation::shutdown () static
Used to signify the end of simulation.
Cleans up any existing Simulation Objects
The documentation for this class was generated from the following files:
src/sst/core/simulation.h
src/sst/core/simulation.cc
src/sst/core/statapi/componentregisterstat_impl.h