SST: SST::SSTInfoElement_LibraryInfo Class Reference
SST::SSTInfoElement_LibraryInfo Class Reference
The SSTInfo representation of ElementLibraryInfo object.
#include <sstinfo.h>
Public Member Functions
SSTInfoElement_LibraryInfo (const ElementLibraryInfo *eli)
Create a new SSTInfoElement_LibraryInfo object.
std::string getLibraryName ()
Return the Name of the Library.
std::string getLibraryDescription ()
Return the Description of the Library.
int getNumberOfLibraryComponents ()
Return the number of Components within the Library.
int getNumberOfLibraryIntrospectors ()
Return the number of Introspectors within the Library.
int getNumberOfLibraryEvents ()
Return the number of Events within the Library.
int getNumberOfLibraryModules ()
Return the number of Modules within the Library.
int getNumberOfLibrarySubComponents ()
Return the number of SubComponents within the Library.
int getNumberOfLibraryPartitioners ()
Return the number of Partitioners within the Library.
int getNumberOfLibraryGenerators ()
Return the number of Generators within the Library.
const ElementLibraryInfo * getLibraryInfo ()
Return the ElementLibraryInfo object.
SSTInfoElement_ComponentInfo * getInfoComponent (int Index)
Return a specific SSTInfoElement_ComponentInfo object.
SSTInfoElement_IntrospectorInfo * getInfoIntrospector (int Index)
Return a specific SSTInfoElement_IntrospectorInfo object.
SSTInfoElement_EventInfo * getInfoEvent (int Index)
Return a specific SSTInfoElement_EventInfo object.
SSTInfoElement_ModuleInfo * getInfoModule (int Index)
Return a specific SSTInfoElement_ModuleInfo object.
SSTInfoElement_SubComponentInfo * getInfoSubComponent (int Index)
Return a specific SSTInfoElement_SubComponentInfo object.
SSTInfoElement_PartitionerInfo * getInfoPartitioner (int Index)
Return a specific SSTInfoElement_PartitionerInfo object.
SSTInfoElement_GeneratorInfo * getInfoGenerator (int Index)
Return a specific SSTInfoElement_GeneratorInfo object.
void outputLibraryInfo (int LibIndex)
Output the Library Information.
void generateLibraryInfoXMLData (int LibIndex, TiXmlNode *XMLParentElement)
Create the formatted XML data of the Library.
Detailed Description
The SSTInfo representation of ElementLibraryInfo object.
This class is used internally by SSTInfo to load and process ElementLibraryInfo objects.
Constructor & Destructor Documentation
SST::SSTInfoElement_LibraryInfo::SSTInfoElement_LibraryInfo (const ElementLibraryInfo * eli) inline
Create a new SSTInfoElement_LibraryInfo object.
Parameters
eli Pointer to an ElementLibraryInfo object.
Member Function Documentation
void SSTInfoElement_LibraryInfo::generateLibraryInfoXMLData (int LibIndex, TiXmlNode * XMLParentElement)
Create the formatted XML data of the Library.
Parameters
LibIndex The Index of the Library.
XMLParentElement The parent element to receive the XML data.
References SST::SSTInfoElement_ComponentInfo::generateComponentInfoXMLData(), SST::SSTInfoElement_EventInfo::generateEventInfoXMLData(), SST::SSTInfoElement_GeneratorInfo::generateGeneratorInfoXMLData(), SST::SSTInfoElement_IntrospectorInfo::generateIntrospectorInfoXMLData(), SST::SSTInfoElement_ModuleInfo::generateModuleInfoXMLData(), and SST::SSTInfoElement_PartitionerInfo::generatePartitionerInfoXMLData().
SSTInfoElement_ComponentInfo* SST::SSTInfoElement_LibraryInfo::getInfoComponent (int Index) inline
Return a specific SSTInfoElement_ComponentInfo object.
Parameters
Index The index of the object.
SSTInfoElement_EventInfo* SST::SSTInfoElement_LibraryInfo::getInfoEvent (int Index) inline
Return a specific SSTInfoElement_EventInfo object.
Parameters
Index The index of the object.
SSTInfoElement_GeneratorInfo* SST::SSTInfoElement_LibraryInfo::getInfoGenerator (int Index) inline
Return a specific SSTInfoElement_GeneratorInfo object.
Parameters
Index The index of the object.
SSTInfoElement_IntrospectorInfo* SST::SSTInfoElement_LibraryInfo::getInfoIntrospector (int Index) inline
Return a specific SSTInfoElement_IntrospectorInfo object.
Parameters
Index The index of the object.
SSTInfoElement_ModuleInfo* SST::SSTInfoElement_LibraryInfo::getInfoModule (int Index) inline
Return a specific SSTInfoElement_ModuleInfo object.
Parameters
Index The index of the object.
SSTInfoElement_PartitionerInfo* SST::SSTInfoElement_LibraryInfo::getInfoPartitioner (int Index) inline
Return a specific SSTInfoElement_PartitionerInfo object.
Parameters
Index The index of the object.
SSTInfoElement_SubComponentInfo* SST::SSTInfoElement_LibraryInfo::getInfoSubComponent (int Index) inline
Return a specific SSTInfoElement_SubComponentInfo object.
Parameters
Index The index of the object.
std::string SST::SSTInfoElement_LibraryInfo::getLibraryDescription () inline
Return the Description of the Library.
References SST::ElementLibraryInfo::description.
const ElementLibraryInfo* SST::SSTInfoElement_LibraryInfo::getLibraryInfo () inline
Return the ElementLibraryInfo object.
std::string SST::SSTInfoElement_LibraryInfo::getLibraryName () inline
Return the Name of the Library.
References SST::ElementLibraryInfo::name.
int SST::SSTInfoElement_LibraryInfo::getNumberOfLibraryComponents () inline
Return the number of Components within the Library.
int SST::SSTInfoElement_LibraryInfo::getNumberOfLibraryEvents () inline
Return the number of Events within the Library.
int SST::SSTInfoElement_LibraryInfo::getNumberOfLibraryGenerators () inline
Return the number of Generators within the Library.
int SST::SSTInfoElement_LibraryInfo::getNumberOfLibraryIntrospectors () inline
Return the number of Introspectors within the Library.
int SST::SSTInfoElement_LibraryInfo::getNumberOfLibraryModules () inline
Return the number of Modules within the Library.
int SST::SSTInfoElement_LibraryInfo::getNumberOfLibraryPartitioners () inline
Return the number of Partitioners within the Library.
int SST::SSTInfoElement_LibraryInfo::getNumberOfLibrarySubComponents () inline
Return the number of SubComponents within the Library.
void SSTInfoElement_LibraryInfo::outputLibraryInfo (int LibIndex)
Output the Library Information.
Parameters
LibIndex The Index of the Library.
References SST::SSTInfoElement_ComponentInfo::getName(), SST::SSTInfoElement_SubComponentInfo::getName(), SST::SSTInfoElement_ComponentInfo::outputComponentInfo(), SST::SSTInfoElement_EventInfo::outputEventInfo(), SST::SSTInfoElement_GeneratorInfo::outputGeneratorInfo(), SST::SSTInfoElement_IntrospectorInfo::outputIntrospectorInfo(), SST::SSTInfoElement_ModuleInfo::outputModuleInfo(), SST::SSTInfoElement_PartitionerInfo::outputPartitionerInfo(), and SST::SSTInfoElement_SubComponentInfo::outputSubComponentInfo().
The documentation for this class was generated from the following files:
src/sst/core/sstinfo.h
src/sst/core/sstinfo.cc