SST: SST::Statistics::StatisticProcessingEngine Class Reference
SST::Statistics::StatisticProcessingEngine Class Reference
An SST core component that handles timing and event processing informing all registered Statistics to generate their outputs at desired rates.
#include <statengine.h>
Public Member Functions
void performStatisticOutput (StatisticBase *stat, bool endOfSimFlag=false)
Called by the Components and Subcomponent to perform a statistic Output.
void performGlobalStatisticOutput (bool endOfSimFlag=false)
Called by the Components and Subcomponent to perform a global statistic Output.
Friends
class SST::Component
class SST::Simulation
Detailed Description
An SST core component that handles timing and event processing informing all registered Statistics to generate their outputs at desired rates.
Member Function Documentation
void SST::Statistics::StatisticProcessingEngine::performGlobalStatisticOutput (bool endOfSimFlag = false)
Called by the Components and Subcomponent to perform a global statistic Output.
This routine will force ALL Components and Subcomponents to output their statistic information. This may lead to unexpected results if the statistic counts or data is reset on output.
Parameters
endOfSimFlag - Indicates that the output is occurring at the end of simulation.
References performStatisticOutput().
void SST::Statistics::StatisticProcessingEngine::performStatisticOutput (StatisticBase * stat, bool endOfSimFlag = false)
Called by the Components and Subcomponent to perform a statistic Output.
Parameters
stat - Pointer to the statistic.
EndOfSimFlag - Indicates that the output is occuring at the end of simulation.
References SST::Statistics::StatisticBase::clearStatisticData(), SST::Statistics::StatisticBase::getFlagClearDataOnOutput(), SST::Statistics::StatisticBase::getFlagResetCountOnOutput(), SST::Simulation::getSimulation(), SST::Statistics::StatisticBase::isOutputEnabled(), and SST::Statistics::StatisticBase::resetCollectionCount().
Referenced by performGlobalStatisticOutput().
The documentation for this class was generated from the following files:
src/sst/core/statapi/statengine.h
src/sst/core/statapi/statengine.cc