SST: SST::Statistics::StatisticOutputCSV Class Reference
SST::Statistics::StatisticOutputCSV Class Reference
The class for statistics output to a comma separated file.
#include <statoutputcsv.h>
Public Member Functions
StatisticOutputCSV (Params &outputParameters)
Construct a StatOutputCSV.
Public Member Functions inherited from SST::Statistics::StatisticOutput
StatisticOutput (Params &outputParameters)
Construct a base StatisticOutput.
std::string & getStatisticOutputName ()
Return the Statistic Output name.
uint8_t getStatisticLoadLevel ()
Return the statistics load level for the system.
Params & getOutputParameters ()
Return the parameters for the StatisticOutput.
template<typename T >
fieldHandle_t registerField (const char *fieldName)
Register a field to be output (templated function)
StatisticFieldInfo * getRegisteredField (fieldHandle_t fieldHandle)
Adjust the heirarchy of the fields (FUTURE SUPPORT)
template<typename T >
StatisticFieldInfo * getRegisteredField (const char *statisticName, const char *fieldName)
Return the information on a registered field via known names.
FieldInfoArray_t & getFieldInfoArray ()
Return the array of registered field infos.
void outputField (fieldHandle_t fieldHandle, int32_t data)
Output field data.
void outputField (fieldHandle_t fieldHandle, uint32_t data)
void outputField (fieldHandle_t fieldHandle, int64_t data)
void outputField (fieldHandle_t fieldHandle, uint64_t data)
void outputField (fieldHandle_t fieldHandle, float data)
void outputField (fieldHandle_t fieldHandle, double data)
const char * getFieldTypeShortName (fieldType_t type)
Output field data.
Protected Member Functions
bool checkOutputParameters ()
Perform a check of provided parameters.
void printUsage ()
Print out usage for this Statistic Output.
void startOfSimulation ()
Indicate to Statistic Output that simulation started.
void endOfSimulation ()
Indicate to Statistic Output that simulation ended.
void implStartOutputEntries (StatisticBase *statistic)
Implementation function for the start of output.
void implStopOutputEntries ()
Implementation function for the end of output.
void implOutputField (fieldHandle_t fieldHandle, int32_t data)
Implementation functions for output.
void implOutputField (fieldHandle_t fieldHandle, uint32_t data)
void implOutputField (fieldHandle_t fieldHandle, int64_t data)
void implOutputField (fieldHandle_t fieldHandle, uint64_t data)
void implOutputField (fieldHandle_t fieldHandle, float data)
void implOutputField (fieldHandle_t fieldHandle, double data)
Protected Member Functions inherited from SST::Statistics::StatisticOutput
friend int::main (int argc, char **argv)
void setStatisticOutputName (std::string name)
void lock ()
void unlock ()
Additional Inherited Members
Public Types inherited from SST::Statistics::StatisticOutput
typedef StatisticFieldInfo::fieldType_t fieldType_t
typedef StatisticFieldInfo::fieldHandle_t fieldHandle_t
typedef std::vector< StatisticFieldInfo * > FieldInfoArray_t
typedef std::unordered_map< std::string, fieldHandle_t > FieldNameMap_t
Detailed Description
The class for statistics output to a comma separated file.
Constructor & Destructor Documentation
SST::Statistics::StatisticOutputCSV::StatisticOutputCSV (Params & outputParameters)
Construct a StatOutputCSV.
Parameters
outputParameters - Parameters used for this Statistic Output
References SST::Simulation::getSimulationOutput(), and SST::Output::verbose().
Member Function Documentation
bool SST::Statistics::StatisticOutputCSV::checkOutputParameters () protected virtual
Perform a check of provided parameters.
Returns
True if all required parameters and options are acceptable
Implements SST::Statistics::StatisticOutput.
References SST::Params::find(), and SST::Statistics::StatisticOutput::getOutputParameters().
void SST::Statistics::StatisticOutputCSV::endOfSimulation () protected virtual
Indicate to Statistic Output that simulation ended.
Statistic output may perform any shutdown code here as necessary.
Implements SST::Statistics::StatisticOutput.
void SST::Statistics::StatisticOutputCSV::implOutputField (fieldHandle_t fieldHandle, int32_t data) protected virtual
Implementation functions for output.
These will be called by the statistic to provide Statistic defined data to be output.
Parameters
fieldHandle - The handle to the registered statistic field.
data - The data related to the registered field to be output.
Implements SST::Statistics::StatisticOutput.
void SST::Statistics::StatisticOutputCSV::implStartOutputEntries (StatisticBase * statistic) protected virtual
Implementation function for the start of output.
This will be called by the Statistic Processing Engine to indicate that a Statistic is about to send data to the Statistic Output for processing.
Parameters
statistic - Pointer to the statistic object than the output can retrieve data from.
Implements SST::Statistics::StatisticOutput.
References SST::Statistics::StatisticBase::getCompName(), SST::Statistics::StatisticOutput::getFieldInfoArray(), SST::Statistics::StatisticBase::getStatName(), SST::Statistics::StatisticBase::getStatSubId(), and SST::Statistics::StatisticBase::getStatTypeName().
void SST::Statistics::StatisticOutputCSV::implStopOutputEntries () protected virtual
Implementation function for the end of output.
This will be called by the Statistic Processing Engine to indicate that a Statistic is finished sendind data to the Statistic Output for processing. The Statisic Output can perform any output related functions here.
Implements SST::Statistics::StatisticOutput.
References SST::Simulation::getSimulation().
void SST::Statistics::StatisticOutputCSV::startOfSimulation () protected virtual
Indicate to Statistic Output that simulation started.
Statistic output may perform any startup code here as necessary.
Implements SST::Statistics::StatisticOutput.
References SST::Output::fatal(), SST::Statistics::StatisticOutput::getFieldInfoArray(), SST::Statistics::StatisticFieldInfo::getFieldName(), SST::Statistics::StatisticFieldInfo::getFieldType(), SST::Statistics::StatisticOutput::getFieldTypeShortName(), SST::Simulation::getRank(), SST::Simulation::getSimulation(), and SST::Simulation::getSimulationOutput().
The documentation for this class was generated from the following files:
src/sst/core/statapi/statoutputcsv.h
src/sst/core/statapi/statoutputcsv.cc