SST: SST::ThreadSync Class Reference
SST::ThreadSync Class Reference
Public Member Functions
ThreadSync (int num_threads, Simulation *sim)
Create a new ThreadSync object.
void setMaxPeriod (TimeConverter *period)
void registerLink (LinkId_t link_id, Link *link)
Register a Link which this Sync Object is responsible for.
ActivityQueue * getQueueForThread (int tid)
void execute (void)
Function which will be called when the time for this Activity comes to pass.
void processLinkInitData ()
Cause an exchange of Initialization Data to occur.
void finalizeLinkConfigurations ()
Finish link configuration.
uint64_t getDataSize () const
void print (const std::string &header, Output &out) const
Generic print-print function for this Activity.
Public Member Functions inherited from SST::Activity
void setDeliveryTime (SimTime_t time)
Set the time for which this Activity should be delivered.
SimTime_t getDeliveryTime () const
Return the time at which this Activity will be delivered.
int getPriority () const
Return the Priority of this Activity.
void setQueueOrder (uint64_t order)
Set a new Queue order.
Public Member Functions inherited from SST::Core::Serialization::serializable
virtual const char * cls_name () const =0
virtual uint32_t cls_id () const =0
Static Public Member Functions
static void disable ()
Additional Inherited Members
Protected Types inherited from SST::Core::Serialization::serializable
enum cxn_flag_t { ConstructorFlag }
Protected Member Functions inherited from SST::Action
void endSimulation ()
Called to signal to the Simulation object to end the simulation.
void endSimulation (SimTime_t end)
Protected Member Functions inherited from SST::Activity
void setPriority (int priority)
Set the priority of the Activity.
void serialize_order (SST::Core::Serialization::serializer &ser)
Static Protected Member Functions inherited from SST::Core::Serialization::serializable
static void serializable_abort (uint32_t line, const char *file, const char *func, const char *obj)
Protected Attributes inherited from SST::Activity
int32_t enforce_link_order
Member Function Documentation
void SST::ThreadSync::execute (void) virtual
Function which will be called when the time for this Activity comes to pass.
Implements SST::Activity.
References SST::Action::endSimulation(), SST::Simulation::getCurrentSimCycle(), SST::Activity::getDeliveryTime(), SST::Simulation::getExit(), SST::TimeConverter::getFactor(), SST::Event::getLinkId(), SST::Simulation::insertActivity(), and SST::Core::ThreadSafe::Barrier::wait().
void SST::ThreadSync::print (const std::string & header, Output & out) const virtual
Generic print-print function for this Activity.
Subclasses should override this function.
Reimplemented from SST::Action.
References SST::Activity::getDeliveryTime(), SST::TimeConverter::getFactor(), SST::Activity::getPriority(), and SST::Output::output().
The documentation for this class was generated from the following files:
src/sst/core/threadSync.h
src/sst/core/threadSync.cc