SST: SST::SSTInfoElement_ComponentInfo Class Reference
SST::SSTInfoElement_ComponentInfo Class Reference
The SSTInfo representation of ElementInfoComponent object.
#include <sstinfo.h>
Public Member Functions
SSTInfoElement_ComponentInfo (const ElementInfoComponent *elc)
Create a new SSTInfoElement_ComponentInfo object.
const char * getName ()
Return the Name of the Component.
const char * getDesc ()
Return the Description of the Component.
SSTInfoElement_ParamInfo * getParamInfo (int index)
Return a Parameter Info Object.
SSTInfoElement_PortInfo * getPortInfo (int index)
Return a Port Info Object.
SSTInfoElement_StatisticInfo * getStatisticInfo (int index)
Return a Statistic Enable Info Object.
uint32_t getCategoryValue ()
Return the Category value of the Component.
const char * getCategoryString ()
Return the name of the Category of the Component.
void outputComponentInfo (int Index)
Output the Component Information.
void generateComponentInfoXMLData (int Index, TiXmlNode *XMLParentElement)
Create the formatted XML data of the Component.
Detailed Description
The SSTInfo representation of ElementInfoComponent object.
This class is used internally by SSTInfo to load and process ElementInfoComponent objects.
Constructor & Destructor Documentation
SST::SSTInfoElement_ComponentInfo::SSTInfoElement_ComponentInfo (const ElementInfoComponent * elc) inline
Create a new SSTInfoElement_ComponentInfo object.
Parameters
elc Pointer to an ElementInfoComponent object.
References SST::ElementInfoComponent::params, SST::ElementInfoComponent::ports, and SST::ElementInfoComponent::stats.
Member Function Documentation
void SSTInfoElement_ComponentInfo::generateComponentInfoXMLData (int Index, TiXmlNode * XMLParentElement)
Create the formatted XML data of the Component.
Parameters
Index The Index of the Component.
XMLParentElement The parent element to receive the XML data.
Referenced by SST::SSTInfoElement_LibraryInfo::generateLibraryInfoXMLData().
const char* SST::SSTInfoElement_ComponentInfo::getCategoryString () inline
Return the name of the Category of the Component.
uint32_t SST::SSTInfoElement_ComponentInfo::getCategoryValue () inline
Return the Category value of the Component.
References SST::ElementInfoComponent::category.
const char* SST::SSTInfoElement_ComponentInfo::getDesc () inline
Return the Description of the Component.
References SST::ElementInfoComponent::description.
const char* SST::SSTInfoElement_ComponentInfo::getName () inline
Return the Name of the Component.
References SST::ElementInfoComponent::name.
Referenced by SST::SSTInfoElement_LibraryInfo::outputLibraryInfo().
SSTInfoElement_ParamInfo* SST::SSTInfoElement_ComponentInfo::getParamInfo (int index) inline
Return a Parameter Info Object.
Parameters
index The index of the Parameter.
SSTInfoElement_PortInfo* SST::SSTInfoElement_ComponentInfo::getPortInfo (int index) inline
Return a Port Info Object.
Parameters
index The index of the Port.
SSTInfoElement_StatisticInfo* SST::SSTInfoElement_ComponentInfo::getStatisticInfo (int index) inline
Return a Statistic Enable Info Object.
Parameters
index The index of the Statistic Enable.
void SSTInfoElement_ComponentInfo::outputComponentInfo (int Index)
Output the Component Information.
Parameters
Index The Index of the Component.
Referenced by SST::SSTInfoElement_LibraryInfo::outputLibraryInfo().
The documentation for this class was generated from the following files:
src/sst/core/sstinfo.h
src/sst/core/sstinfo.cc