#!/bin/bash
#SBATCH -D /ufrc/lam/saravana8394/sst-elements-library-6.0.0/src/sst/elements/behavioralEmulation/tests
#SBATCH --job-name=be_sim-es11ec64np1048576.job
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=saravana8394@ufl.edu
#SBATCH --account=ccmt
#SBATCH --qos=ccmt
#SBATCH --ntasks=64
#SBATCH --cpus-per-task=4
#SBATCH --nodes=8
#SBATCH --mem=240gb
#SBATCH --ntasks-per-socket=4
#SBATCH --distribution=cyclic:block
#SBATCH --partition=hpg1-compute
#SBATCH -t 12:20:00
#SBATCH -o titan-job/1048576-hpg1compute.csv
#SBATCH -e titan-job/err/1048576-hpg1compute.err
 
module purge
ml add ufrc
ml add gcc/5.2.0 python boost/1.59.0 openmpi/1.10.2
export SST_CORE_HOME=/ufrc/lam/saravana8394/sstcore-6.0.0/mycore
export SST_ELEMENT_HOME=/ufrc/lam/saravana8394/sst-elements-library-6.0.0/sst_element_new
export PATH=${SST_ELEMENT_HOME}/bin:${SST_CORE_HOME}/bin:$PATH
 
./BE_RUN.sh -c titan-proper-es11ec64np1048576.py -n 64 -v
